export const GET_FILMS_REQUEST = 'GET_FILMS_REQUEST';
export const GET_FILMS_SUCCESS = 'GET_FILMS_SUCCESS';
export const GET_FILMS_FAILED = 'GET_FILMS_FAILED';
export const GET_SEARCH_REQUEST = 'GET_SEARCH_REQUEST';
export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS';
export const GET_SEARCH_FAILED = 'GET_SEARCH_FAILED';
export const ADD_FILM_FAVORITE = 'ADD_FILM_FAVORITE';
export const DELETE_FILM_FAVORITE = 'DELETE_FILM_FAVORITE';
export const GET_FILM_ID = 'GET_FILM_ID';
export const FILTER_FILMS = 'FILTER_FILMS';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const ADD_FILM_FAVORITE_IS_LOGIN = 'ADD_FILM_FAVORITE_IS_LOGIN';
export const DELETE_FILM_FAVORITE_IS_LOGIN = 'DELETE_FILM_FAVORITE_IS_LOGIN';
export const WATCHED_FILM = 'WATCHED_FILM';
export const DELETE_WATCHED_FILM = 'DELETE_WATCHED_FILM';
export const DELETE_WATCHED_FILM_OFF = 'DELETE_WATCHED_FILM_OFF';

